runtime: php
env: flex
runtime_config:
    document_root: .
env_variables:
    APP_LOG: errorlog
    GOOGLE_STORAGE_BUCKET: "black-outlet-275318.appspot.com"
    MYSQL_USER: "inglemar"
    MYSQL_PASSWORD: "40927745729"
    MYSQL_DSN: "mysql:dbname=mesas_interactivas;unix_socket=/cloudsql/black-outlet-275318:southamerica-east1:bd-mesa-interactiva"
beta_settings:
    cloud_sql_instances: "black-outlet-275318:southamerica-east1:bd-mesa-interactiva"
